/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FreezeRequest } from "./FreezeRequest";
import { FreezeRequestCountArgs } from "./FreezeRequestCountArgs";
import { FreezeRequestFindManyArgs } from "./FreezeRequestFindManyArgs";
import { FreezeRequestFindUniqueArgs } from "./FreezeRequestFindUniqueArgs";
import { DeleteFreezeRequestArgs } from "./DeleteFreezeRequestArgs";
import { FreezeRequestService } from "../freezeRequest.service";
@graphql.Resolver(() => FreezeRequest)
export class FreezeRequestResolverBase {
  constructor(protected readonly service: FreezeRequestService) {}

  async _freezeRequestsMeta(
    @graphql.Args() args: FreezeRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FreezeRequest])
  async freezeRequests(
    @graphql.Args() args: FreezeRequestFindManyArgs
  ): Promise<FreezeRequest[]> {
    return this.service.freezeRequests(args);
  }

  @graphql.Query(() => FreezeRequest, { nullable: true })
  async freezeRequest(
    @graphql.Args() args: FreezeRequestFindUniqueArgs
  ): Promise<FreezeRequest | null> {
    const result = await this.service.freezeRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FreezeRequest)
  async deleteFreezeRequest(
    @graphql.Args() args: DeleteFreezeRequestArgs
  ): Promise<FreezeRequest | null> {
    try {
      return await this.service.deleteFreezeRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
